language: python
python:
- 3.6
env:
  matrix:
  - PACKAGENAME=jsoncpp
  global:
    secure: SUqcGP1m1DefRH7ViCbxB3k9Oi0MWneP1SIwpmSS+QFnjK5c1/zUBvuhoJ7cBIh0o3KJXDvYUvLMSZ4mKbTSG61gtHqGwzlRe6OFTpn6PgU/DeG56bKRWnfr3fr6P1OU0XQ6nkocsuxNxvlqkrvQ39+2G0oEY39IhMbjcl1Ldk/0gSpAUhwaQ5M+60eYymd3Tt2fnebFgaOZYL7ZM8Weq/iXmk+EaVO6g1EZ4Aeao3Dpz3GY4Y506OVichNGYcCfsE/HPLdEDqzvWjRNDjT00chxmRcqPBaBIY8SqMTQefCN2/fOoWpvklG4zkZJJADtH40c5kh+aHmdnppPDQN9/29B2jI6UXR4UGRsGxv/83KA5ufETPUfP9hMNIfDOtS7DeDKMSAOgapfM/79gYhP/BnIJBVOKDdz7RiDARhx4SnZaT9d9cqHcEJsNkHUu9j2JiU8D4o60sNH3qUbAExIWMkGi33WAiMXvBHX3VDlDYa2Liwyd8hIQsEwrT/b4t/TSycbGko2ZaRiukdfDY0uHdxyBUyIb8AvamUs/oPRqkHHESqVGkFFhSb6OkGhIRg84bqnWnG6JsMUvK4r/z0hREEPw6C4AuyhZI0ONKyo8ExDlZ3YbuzO7GvI3HRSAQMn1+dYxBnLY8HVVSoa6C1H9tsCFS3tYCZdwvioZoTqA2k=
before_install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- "./miniconda.sh -b"
- export PATH=$HOME/miniconda3/bin:$PATH
- conda update --yes -q conda
- conda config --set always_yes true
- conda config --set anaconda_upload no
install:
- conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION
- source activate test-env
- conda install conda-build
- conda install anaconda-client
- conda build conda-recipe
- conda install --use-local $PACKAGENAME
after_success:
- anaconda -t $ANACONDA_TOKEN upload $HOME/miniconda3/envs/test-env/conda-bld/linux-64/jsoncpp-*.tar.bz2
skip_cleanup: true
